stages:
  load_data:
    cmd: python src\load_data.py --config=params.yaml
    deps:
    - src\get_data.py
    - src\load_data.py
    - data_given\EnergyData.csv
    outs:
    - data\raw\EnergyData.csv

  split_data:
    cmd: python src\split_data.py --config=params.yaml
    deps:
    - src\split_data.py
    - data\raw\EnergyData.csv
    outs:
    - data\processed\train_EnergyData.csv
    - data\processed\test_EnergyData.csv