stages:
  load_data:
    cmd: python src\load_data.py --config=params.yaml
    deps:
    - src\get_data.py
    - src\load_data.py
    - data_given\EnergyData.csv
    outs:
    - data\raw\EnergyData.csv

  split_data:
    cmd: python src\split_data.py --config=params.yaml
    deps:
    - src\split_data.py
    - data\raw\EnergyData.csv
    outs:
    - data\processed\train_EnergyData.csv
    - data\processed\test_EnergyData.csv

  train_and_evaluate:
    cmd: python src\train_and_evaluate.py --config=params.yaml
    deps:
      - data\processed\train_EnergyData.csv
      - data\processed\test_EnergyData.csv
      - src\train_and_evaluate.py
    params:
      - estimators.RandomForestRegressor.params.max_depth
      - estimators.RandomForestRegressor.params.max_features
      - estimators.RandomForestRegressor.params.n_estimators
    # metrics:
    #   - reports\scores.json:
    #       cache: false
    #   - reports\params.json:
    #       cache: false
    # outs:
    #   - saved_model\model.joblib
    #   - saved_model\model2.joblib

  log_production_model:
    cmd: python src\log_production_model.py --config=params.yaml
    deps:
      - src/log_production_model.py