base:
  project: Energy-Efficiency
  random_state: 42
  target_col1: heating_load
  target_col2: cooling_load

data_source:
  s3_source: data_given\EnergyData.csv

load_data:
  raw_dataset_csv: data\raw\EnergyData.csv

split_data:
  train_path: data\processed\train_EnergyData.csv
  test_path: data\processed\test_EnergyData.csv
  test_size: 0.2

estimators:
  RandomForestRegressor:
    params:
      max_depth: 85
      max_features: 2
      n_estimators: 350
      # bootstrap= True

  Ridge:
    params:
      alpha=0.1
      
model_dir: saved_model

reports:
  params: reports\params.json
  scores: reports\scores.json

webapp_model_dir: 
  model1: prediction_service/model/model.joblib
  model2: prediction_service/model/model2.joblib